name: qr_image
description: A starting point for Dart libraries or applications.
version: 1.0.0
repository: https://github.com/leamlidara/qr_image_dart

environment:
    sdk: ">=2.19.2 <3.0.0"

platforms:
    linux:
    macos:
    windows:

dependencies:
    qr: ^3.0.1
    image: ^4.0.15
#   path: ^1.8.0

dev_dependencies:
    lints: ^2.0.0
    test: ^1.21.0
